In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]

In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5 5 5 5 5 5 5 5 5 5]
 [10 11 12 13 14 15 16 17 18 19]

In [3]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0003897622754884811 0.9937481599653342 0.4750927189805273

In [4]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False

In [6]:
arr = np. array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]

In [3]:
import numpy as np
arr = np.zeros((8, 8))
arr[1::2, ::2], arr[::2, 1::2] = (1, 1)
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]

In [6]:
import numpy as np
print(np.full((5, 5), np.arange(5)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

In [7]:
import numpy as np
print(np.random.random((3, 3, 3)))

[[[0.39252938 0.15686493 0.65333668]
  [0.34265537 0.45689461 0.24602881]
  [0.73475287 0.05006414 0.7720467 ]]

 [[0.50391968 0.99834301 0.94718349]
  [0.94511257 0.67646377 0.62868803]
  [0.78181557 0.92596387 0.135802  ]]

 [[0.29957687 0.36447863 0.23295184]
  [0.07327841 0.94163793 0.50973136]
  [0.24677297 0.89526886 0.38523062]]]

In [21]:
import numpy as np
arr = np.ones((7, 5))
arr[1:arr.shape[0]-1, 1:arr.shape[1]-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

In [26]:
import numpy as np
arr = np.arange(10)
arr = -np.sort(-arr)
print(arr)

[9 8 7 6 5 4 3 2 1 0]

In [36]:
import numpy as np
arr = np.random.random((5, 5))
print("Форма:", arr.shape, "Размер:", arr.size, "Размерность:", arr.ndim)

Форма: (5, 5) Размер: 25 Размерность: 2

In [9]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64

In [11]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

                Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

In [22]:
# URL из примера недоступен, поэтому я нашел другой с Титаником
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

dataframe.head(2)
dataframe. tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['Pclass'] == 1].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [37]:
import pandas as pd
import numpy as np

a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

dist = np.sqrt(((a - b)**2).sum())
print(dist)

5.196152422706632

In [62]:
import pandas as pd
dataframe = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/adult.csv")
# dataframe.head(2)
# dataframe.tail(3)
# dataframe.shape
# dataframe.describe()
# dataframe.iloc[1:4]
dataframe[dataframe["age"] == 50].head(2)

,age,workclass,education_num,marital_status,occupation,relationship,race,gender,hours_per_week,native_country,capital,income_status
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,0,<=50K
49,50,Federal-gov,13,Divorced,Exec-managerial,Not-in-family,White,Male,55,United-States,0,>50K

In [24]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing
# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)
#Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [26]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
print(standardized)

print("Среднее: ", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее:  0
Стандартное отклонение: 1.0

In [28]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                           'B':[103.02,107.26,110.35,114.23,114.68],
                           'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

          A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [74]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
data = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
data[["sepal_length_cm"]] = MinMaxScaler().fit_transform(data[["sepal_length_cm"]])
data[["sepal_width_cm"]] = StandardScaler().fit_transform(data[["sepal_width_cm"]])
data

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,0.222222,1.032057,1.4,0.2,setosa
1,0.166667,-0.124958,1.4,0.2,setosa
2,0.111111,0.337848,1.3,0.2,setosa
3,0.083333,0.106445,1.5,0.2,setosa
4,0.194444,1.263460,1.4,0.2,setosa
...,...,...,...,...,...
145,0.666667,-0.124958,5.2,2.3,virginica
146,0.555556,-1.281972,5.0,1.9,virginica
147,0.611111,-0.124958,5.2,2.0,virginica
148,0.527778,0.800654,5.4,2.3,virginica
149,0.444444,-0.124958,5.1,1.8,virginica